// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJQBjatbjpfIgvGKz_rluqM0BH_bdIM4',
    appId: '1:947478666377:web:d7b37ff277168532faba58',
    messagingSenderId: '947478666377',
    projectId: 'my-books-6017b',
    authDomain: 'my-books-6017b.firebaseapp.com',
    storageBucket: 'my-books-6017b.firebasestorage.app',
    measurementId: 'G-HF5JRH1N5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Z-wTYDNSqcvZ3XrW61XsZD1-9fAu7c0',
    appId: '1:947478666377:android:a02cf4b3ed868f63faba58',
    messagingSenderId: '947478666377',
    projectId: 'my-books-6017b',
    storageBucket: 'my-books-6017b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEF-iBNpufcnpXNSRieZ2Ow012UUPOG_4',
    appId: '1:947478666377:ios:d2dc4933f9a66ae1faba58',
    messagingSenderId: '947478666377',
    projectId: 'my-books-6017b',
    storageBucket: 'my-books-6017b.firebasestorage.app',
    iosBundleId: 'com.example.myBooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEF-iBNpufcnpXNSRieZ2Ow012UUPOG_4',
    appId: '1:947478666377:ios:d2dc4933f9a66ae1faba58',
    messagingSenderId: '947478666377',
    projectId: 'my-books-6017b',
    storageBucket: 'my-books-6017b.firebasestorage.app',
    iosBundleId: 'com.example.myBooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFJQBjatbjpfIgvGKz_rluqM0BH_bdIM4',
    appId: '1:947478666377:web:6eaf00117ebdd645faba58',
    messagingSenderId: '947478666377',
    projectId: 'my-books-6017b',
    authDomain: 'my-books-6017b.firebaseapp.com',
    storageBucket: 'my-books-6017b.firebasestorage.app',
    measurementId: 'G-L9MS0FNLW8',
  );
}
